# Generated by Django 3.2.6 on 2023-03-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_update_product_updated'),
        ('shop', '0003_auto_20220214_2155'),
    ]

    operations = [
    ]
